### ISSUE TITLE
Create packet class

### ISSUE THREAD

**Issue by sudo-Eric** [CSC-CLU/VEXnetDriver#2]
Change the driver to use a class representing packets with communication support functions instead of a class representing communication alone.

**Comment by Zrp200** [comment]
do you want the class itself to handle sending and receiving, or can the send/receive code be in the driver?

If the class needs to handle sending and receiving, it will need a dedicated reference to the driver instance.

**Comment by Zrp200** [comment]
The easiest thing I can imagine is doing something like this:

```c++
struct VexProtocolPacket {
    unsigned char type, size, *data = new unsigned char[100];

    ~VexProtocolPacket() { delete[] data; }
}
```
and from there replacing the methods that use the three fields with one that takes either a reference or a pointer to `VexProtocolPacket`. It also would probably eliminate the need for the buffer if coded correctly.

Am I misinterpreting this?
